### ISSUE TITLE
IndexError: too many indices for array (when running covar batch)

### ISSUE THREAD

**Issue by ChrisGottsacker** [Parks-Laboratory/epistasis_pipeline#3]
The root cause is line 128 of [epistasis_pipeline/scripts/epistasis_node.py](url): 

Traceback (most recent call last):
    File "epistasis_node.py", line 200, in <module>
        run_fastlmmc(dataset, output_dir, process_id, group_size, covFile, species, maxthreads, featsel=featsel, exclude=exclude, condition=condition)

    File "epistasis_node.py", line 128, in run_fastlmmc
        df = epistasis(filtered_snp_reader, pheno, G0=full_snp_reader, covar=covFile, sid_list_0=filtered_snp_reader.sid[list_1_idx_start:list_1_idx_end], sid_list_1=filtered_snp_reader.sid[list_2_idx_start:list_2_idx_end])

    File "/wntmp/condor/execute/dir_1551745/glide_mJixsK/execute/dir_3376547/python/lib/python2.7/site-packages/fastlmm/association/epistasis.py", line 105, in epistasis
        logging.info("# of pairs is {0}".format(epistasis.pair_count))

    File "/wntmp/condor/execute/dir_1551745/glide_mJixsK/execute/dir_3376547/python/lib/python2.7/site-packages/fastlmm/association/epistasis.py", line 394, in pair_count
        self._run_once()

    File "/wntmp/condor/execute/dir_1551745/glide_mJixsK/execute/dir_3376547/python/lib/python2.7/site-packages/fastlmm/association/epistasis.py", line 164, in _run_once
        self.pheno = pstpheno.loadOnePhen(self.pheno,vectorize=True) #!! what about missing=-9?

    File "/wntmp/condor/execute/dir_1551745/glide_mJixsK/execute/dir_3376547/python/lib/python2.7/site-packages/pysnptools/util/pheno.py", line 35, in loadOnePhen
        allColumns = loadPhen(filename, missing)

    File "/wntmp/condor/execute/dir_1551745/glide_mJixsK/execute/dir_3376547/python/lib/python2.7/site-packages/pysnptools/util/pheno.py", line 82, in loadPhen
        if data[0,0] == sampid: #One column of ids - use the single id as both the family id and the iid

IndexError: too many indices for array

**Comment by ChrisGottsacker** [comment]
Isn't the cause, but right now the IIDs in *covar* file start at 0, but they have to start at 1 to match up with those in *fam* files.

**Comment by tzrtzr000** [comment]
you mean the value of the IID should start at 1 in _covar_ file?

**Comment by ChrisGottsacker** [comment]
Yep, all IIDs should start at 1, and the IIDs need to match between the *fam*, *covar*, and *pheno* files

**Comment by ChrisGottsacker** [comment]
I ran *epistasis_local.py* to get a *covar* file, and then manually modified the IIDs in Excel so they start at 1 not 0.

Then I deleted the "Covar" column from the *epistasis_local.py* input file and ran *epistasis_local.py* again to get a properly-formatted *pheno* file.

After doing this, epistasis_server.py worked with -c flag (i.e. using covar file).

**Comment by tzrtzr000** [comment]
ok. Currently my _pheno_ files's IID starts at 0... I will fix this and upload a new one on github

**Comment by tzrtzr000** [comment]
I just fixed both problems: IIDs and new feed line and uploaded on github. Thanks for your feedback, Chris!
