### ISSUE TITLE
ERROR: Failed to create proc / AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by ChrisGottsacker** [Parks-Laboratory/epistasis_pipeline#5]
ERROR: Failed to create proc
Number of submitted jobs would exceed MAX_JOBS_PER_SUBMISSION
Traceback (most recent call last):
  File "epistasis_server.py", line 355, in <module>
    process(params)
  File "epistasis_server.py", line 60, in process
    submit_jobs(params)
  File "epistasis_server.py", line 203, in submit_jobs
    condor_cluster = re.search('\d{4,}', condor_cluster).group()
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by ChrisGottsacker** [comment]
Solution: use -g flag to set the group size to something reasonable (e.g. `-g 1500`)
